---
title: "Teaching"
---

Currently I teach in three courses at Eindhoven University of Technology: **Behavioural Research Methods 2 (BRM2)**, **Behavioural Research Methods 3 (BRM3)** and **Metascience**.

### Behavioural Research Methods 2 (BRM2):

- **Introduction to multiple regression**. This lecture
introduces multiple regression analysis, including model specification, interpretation of regression coefficients, model assumptions, and practical applications in R.

<div class="resource-links">

<a href="https://cristianmesquida.github.io/multiple_regression/"
   target="_blank">
  <i class="fa-solid fa-book"></i> Book
</a>

<a href="https://github.com/cristianmesquida/multiple_regression"
   target="_blank">
  <i class="fa-brands fa-github"></i> GitHub
</a>

</div>

- Variable Selection in Multiple Regression: This lecture introduces key concepts such as covariates, confounders, mediators, and colliders. Students learn how to use directed acyclic graphs (DAGs) to guide variable selection in multiple regression, and how the appropriate variables to include depend on whether the research question is causal or associational.

<div class="resource-links">

<a href="https://github.com/cristianmesquida/variable_selection"
   target="_blank">
  <i class="fa-solid fa-person-chalkboard"></i> Slides
</a>

- **Introduction to power analysis** (Chapters 1-5). This
lecture covers the principles of statistical power analysis, its role in study design, and how to perform power analyses for common statistical tests using R.

<div class="resource-links">

<a href="https://cristianmesquida.github.io/power_analysis_brm2-3/#/title-slide"
   target="_blank">
  <i class="fa-solid fa-person-chalkboard"></i> Slides
</a>

<a href="https://cristianmesquida.github.io/doing_power_analysis/"
   target="_blank">
  <i class="fa-solid fa-book"></i> Book
</a>

<a href="https://github.com/cristianmesquida/doing_power_analysis"
   target="_blank">
  <i class="fa-brands fa-github"></i> GitHub
</a>

</div>

### Behavioural Research Methods 3 (BRM3):

- **P-values and Bayes Factors**. This lecture compares Frequentist and Bayesian approaches to statistical inference. 
Students learn how to interpret *p*-values and Bayes
factors and perform Bayesian analyses for paired and independent-samples *t*-tests.

<div class="resource-links">

<a href="https://cristianmesquida.github.io/pvalues_and_bayes/slides.pdf"
   target="_blank">
  <i class="fa-solid fa-person-chalkboard"></i> Slides
</a>

<a href="https://cristianmesquida.github.io/pvalues_and_bayes/"
   target="_blank">
  <i class="fa-brands fa-github"></i> GitHub
</a>

</div>

- **Advanced power analysis** (Chapters 6-8). This lecture focuses on power analysis for more advanced study designs,
including equivalence tests using the `TOSTER` R package, factorial designs using the
`Superpower` R package, and simulation-based approaches in R. 

<div class="resource-links">

<a href="https://cristianmesquida.github.io/power_analysis_brm2-3/#/title-slide"
   target="_blank">
  <i class="fa-solid fa-person-chalkboard"></i> Slides
</a>

<a href="https://cristianmesquida.github.io/doing_power_analysis/"
   target="_blank">
  <i class="fa-brands fa-github"></i> GitHub
</a>

</div>

- **Equivalence testing**. Equivalence testing. In this lecture, I explain the rationale behind equivalence testing, how it differs from traditional null hypothesis significance testing, and how to conduct and interpret equivalence tests using the `TOSTER` R package.

<div class="resource-links">

<a href="https://cristianmesquida.github.io/equivalence_testing/slides.pdf"
   target="_blank">
  <i class="fa-solid fa-person-chalkboard"></i> Slides
</a>

<a href="https://cristianmesquida.github.io/equivalence_testing"
   target="_blank">
  <i class="fa-brands fa-github"></i> GitHub
</a>

</div>

### Metascience

- **Introduction to meta-analysis**. This lecture introduces students to the principles of meta-analysis, including effect size estimation, model fitting, interpretation of results, moderator analysis and assessment of bias using the `meta` R package.

<div class="resource-links">

<a href="https://cristianmesquida.github.io/introduction_to_meta-analysis/#/title-slide"
   target="_blank">
  <i class="fa-solid fa-person-chalkboard"></i> Slides
</a>

<a href="https://github.com/cristianmesquida/introduction_to_meta-analysis"
   target="_blank">
  <i class="fa-brands fa-github"></i> GitHub
</a>

</div>

