---
name: Cristian Mesquida
position: "Postdoctoral Researcher"
address: "Eindhoven University of Technology, The Netherlands"
phone: +34 610 03 85 25 
email: "c.mesquida.caldentey@tue.nl"
www: "cristianmesquida.github.io/cris_blog"
github: "cristianmesquida"
googlescholar: "Cristian Mesquida"
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, results = "asis")

# Load packages
library(vitae)
library(readxl)
library(dplyr)

# Create function to read sheets 
readExcelsheets <- function(filename){
  
  all <- readxl::excel_sheets(filename)
  
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  
  names(list) <- all
  
  list2env(list, envir = .GlobalEnv)
}

# read cv file
filename <- "cv.xlsx"
readExcelsheets(filename)
```

# Employment

```{r}
employment %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = employment, 
                   where = country,
                   why = details)
```

# Education

```{r}
education %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = degree, 
                   where = country,
                   why = details)
```

# Publications

```{r}
bibliography_entries("my_papers.bib") %>%
  arrange(desc(issued))
```

# Preprints

```{r}
bibliography_entries("my_preprints.bib") %>%
  arrange(desc(issued))
```

# Papers in preparation

```{r}
bibliography_entries("in_progress.bib") %>%
  arrange(issued)
```

# Teaching Experience

```{r}

teaching %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = role, 
                   why = details)

```

# Supervision

```{r}

supervision %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = role, 
                   why = details)

```

# Qualifications

```{r}
qualifications %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = position, 
                   where = country,
                   why = details)
```

# Talks

```{r}
talks %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = event,
                   why = details)
```

# Grants

```{r}
grants %>%
  detailed_entries(what = institution, 
                   when = year, 
                   with = grant,
                   why = details)
```

# Conference organization

```{r}
organization %>%
  detailed_entries(what = institution, 
                   when = year,
                   with = event,
                   why = details,
                   where = country)
```

# References

```{r}
references %>%
  detailed_entries(what = institution, 
                   with = reference,
                   why = details,
                   where = country)
```

```{r, include=FALSE}
# save cv.pdf in a second location
file.copy("cv.pdf", "~/Dropbox/cris_blog/_site/cv.pdf", overwrite = TRUE)
```
